#!/bin/sh

# Map <caps lock> to <esc>
setxkbmap -option caps:escape

# Adjust keyboard repeat
xset r rate 175 60

# Adjust screen resolution
xrandr --output DP-4 --mode 2560x1440 --scale 1x1

# Adjust .files in home
# source: << https://wiki.archlinux.org/index.php/XDG_Base_Directory >>
export USERXSESSION="$XDG_CACHE_HOME/x11/xsession"
export USERXSESSIONRC="$XDG_CACHE_HOME/x11/xsessionrc"
export ALTUSERXSESSION="$XDG_CACHE_HOME/x11/Xsession"
export ERRFILE="$XDG_CACHE_HOME/x11/xsession-errors"

# Theme
export QT_STYLE_OVERRIDE=adwaita
export TDESKTOP_USE_GTK_FILE_DIALOG=1
